val any : Typ.t
val empty : Typ.t
val nil : Typ.t
val unit : Typ.t
val arrow : Typ.t
val true_ : Typ.t
val false_ : Typ.t
val bool : Typ.t
val int : Typ.t
val char : Typ.t
val enum : Typ.t
val int8 : Typ.t
val uint8 : Typ.t
val int16 : Typ.t
val uint16 : Typ.t
val int32 : Typ.t
val uint32 : Typ.t
val int64 : Typ.t
val uint64 : Typ.t
val posint : Typ.t
val negint : Typ.t
val by_names : (Base.Hstring.t * Typ.t) list
